# Example configuration file for deep learning training

[data]
data_dir = "data"
batch_size = 32
num_workers = 4
pin_memory = true
train_split = 0.8
val_split = 0.1
test_split = 0.1

[model]
model_type = "cnn"
input_size = 784
hidden_size = 256
num_classes = 10
dropout = 0.1

[training]
max_epochs = 100
learning_rate = 1e-3
weight_decay = 1e-4
scheduler = "cosine"
patience = 10
min_delta = 0.001
accelerator = "auto"
precision = "32"
gradient_clip_val = 1.0
accumulate_grad_batches = 1

[experiment]
name = "example_experiment"
output_dir = "outputs"
log_every_n_steps = 10
val_check_interval = 1.0
save_top_k = 3
monitor = "val_loss"
mode = "min"
seed = 42