# Clippy configuration for workspace projects
avoid-breaking-exported-api = false
msrv = "1.85"

# Comprehensive lints for larger projects
all = "warn"
pedantic = "warn"
nursery = "warn"
cargo = "warn"

# Security-focused lints
unwrap_used = "deny"
expect_used = "deny"

# Allow some pedantic lints that are too strict for larger projects
module_name_repetitions = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"

