# Clippy configuration for workspace projects
avoid-breaking-exported-api = false
msrv = "1.70"

# Comprehensive lints for larger projects
warn = [
    "clippy::all",
    "clippy::pedantic", 
    "clippy::nursery",
    "clippy::cargo",
]

# Security-focused lints
deny = [
    "clippy::unwrap_used",
    "clippy::expect_used",
]

# Allow some pedantic lints that are too strict for larger projects
allow = [
    "clippy::module_name_repetitions",
    "clippy::missing_errors_doc",
    "clippy::missing_panics_doc",
]