[lint]
select = [
    "E",
    "W",    # pycodestyle errors and warnings
    "F",    # Pyflakes
    "I",    # isort
    "N",    # pep8-naming
    "UP",   # pyupgrade
    "ANN",  # flake8-annotations
    "B",    # flake8-bugbear
    "A",    # flake8-builtins
    "C4",   # flake8-comprehensions
    "DTZ",  # flake8-datetimez
    "EM",   # flake8-errmsg
    "FA",   # flake8-future-annotations
    "G",    # flake8-logging-format
    "PIE",  # flake8-pie
    "PT",   # flake8-pytest-style
    "Q",    # flake8-quotes
    "RET",  # flake8-return
    "SIM",  # flake8-simplify
    "ARG",  # flake8-unused-arguments
    "PTH",  # flake8-use-pathlib
    "PERF", # Perflint
    "FURB", # refurb
    "RUF",  # Ruff-specific rules
    "PL",   # Pylint
]

ignore = [
    "E501", # Line length (handled by formatter)
    "D",    # Skip docstring rules for minimal example
]

fixable = ["ALL"]
unfixable = []

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/*" = ["S101", "ARG", "PLR2004"]

[lint.isort]
known-first-party = ["src"]
required-imports = ["from __future__ import annotations"]

[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
