# Clippy configuration for strict code quality
avoid-breaking-exported-api = false
msrv = "1.85"

# Security-focused lints
enum_glob_use = "warn"
pedantic = "warn"
nursery = "warn"

# Deny security-critical lints
unwrap_used = "deny"
expect_used = "deny"

